language: node_js
node_js:
- '11'
addons:
  firefox: latest
cache:
  yarn: true
install:
- npm install -g yarn
- yarn install
- yarn run bootstrap
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
jobs:
  include:
  - stage: Builds
    script: yarn run lint
    name: Lint
  - script: yarn run build:tsc
    name: Node.js Build
  - script: yarn run build:browser
    name: Browser Build
  - stage: Tests
    script: yarn run test:node
    name: Node.js Tests
  - script: yarn run test:browser
    name: Browser Tests
notifications:
  slack:
    secure: ueLjfQ4nLc0+MJnUthnjMsRWmqTG08s92ryeLuz7chxgTSU7wFX9ApRwuuYtyFY+1cslF2zdCiKNwRGPR4qaoEH9Adnn4lNXGSIo37/cO7b2EQWfgq6zTPxLL3ZAndw/PTt5JerBpMru9KBLczoaqOapidThHbUdlng9WJH49tElgwUKpOrrSZvIqZZvWmwSC24HEoteiP3kxGAvJvIn5Dk6L8wC6CKkFq5/m5Q6SBJxwTFSfOlp9rNbi5iyGwq5UBec+HCMbtpD3I5YGkN2fnYQ8C5yM84nK5Nv3c1BeuCGDgEqMHhJ2RWtiGF/apPdSWSTMOaX/cNOfPwIAbD6GrmOOFVkHWsLZb8gQYwFPR/TT8zaCTdXKt1fw4XbOL9wCXxAcvzC9zgX4RqbcVvugEomgydABs44Ba0l1NYfQ3sYPYZkPmA3q+MBcdCG4fWRxyGpkwPmu94yJFsTGQXaJuxlCbWozXZ7C9XLWrsy1cydCJlwxUnI97cAkJmy10y0JZwhfIFJLds1jreupATMAZyO3WZDAmMWzcFw8LkwuNYXOB+2u61dA3fq7vUs0jvSIoV/h8jJu14g5QyRFGF2Bpvew5EzHvTfJnM7cfe/omv38Sr6bbj/kYQS1rZ8t7aYnr/XFY6f/YJ2IeeMOuJvcsHlEXMfkBbOpTwPWg844ZM=
