language: node_js
node_js:
  - "11"
addons:
  firefox: "latest"
before_script:
  - export CHROME_BIN=chromium-browser
jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      script: npm run test
services:
  - xvfb
