language: node_js
node_js:
  - "11"
addons:
  firefox: "latest"
cache:
  yarn: true
install:
  - npm install -g yarn
  - yarn install
  - yarn run bootstrap
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
jobs:
  include:
    - stage: "Builds"
      script: yarn run build:tsc
      name: "Node.js Build"
    - script: yarn run build:browser
      name: "Browser Build"
    - stage: "Tests"
      script: yarn run test:node
      name: "Node.js Tests"
    - script: yarn run test:browser
      name: "Browser Tests"